# -------------------------------------------------------------------------------
# This file has been automatically generated by the Caph compiler (version 2.7.1)
# from file cnn_generated.cph, on 2016-05-08 at 17:11:56, by kamel
# For more information, see : http://caph.univ-bpclermont.fr
# -------------------------------------------------------------------------------

VHDL_GEN_SOURCES = cnn_generated_splitters.vhd cnn_generated_types.vhd cnn_generated_globals.vhd cnn_generated_tb.vhd conv33_act.vhd relu_act.vhd biais_act.vhd poolh_act.vhd poolv_act.vhd hsum_act.vhd vsum_act_act.vhd rep4_act.vhd dot16_act.vhd distr8_act.vhd sum4_act.vhd sum6_act.vhd cnn_generated_net.vhd
VHDL_EXTRA_SOURCES = 
TXT_INPUT_STREAMS = sample.txt
BIN_INPUT_STREAMS = sample.bin
BIN_OUTPUT_STREAMS = w_fc9.bin w_fc8.bin w_fc7.bin w_fc6.bin w_fc5.bin w_fc4.bin w_fc3.bin w_fc2.bin w_fc1.bin w_fc0.bin
TXT_OUTPUT_STREAMS = w_fc9.txt w_fc8.txt w_fc7.txt w_fc6.txt w_fc5.txt w_fc4.txt w_fc3.txt w_fc2.txt w_fc1.txt w_fc0.txt

vhdl.elab:
	$(GHDL) -a $(GHDL_ELAB_OPTS) cnn_generated_splitters.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) cnn_generated_types.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) cnn_generated_globals.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) cnn_generated_tb.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) conv33_act.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) relu_act.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) biais_act.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) poolh_act.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) poolv_act.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) hsum_act.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) vsum_act_act.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) rep4_act.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) dot16_act.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) distr8_act.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) sum4_act.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) sum6_act.vhd
	$(GHDL) -a $(GHDL_ELAB_OPTS) cnn_generated_net.vhd
	$(GHDL) -e $(GHDL_ELAB_OPTS) cnn_generated_tb
